const knowledgeBase = {
    "hello": "Hello! How can I assist you today?",
    "hi": "Hi there! How may I help you?",
    "who are you": "I am a Bonet Elite Agent, here to assist you.",
    "what services do you offer": "We provide Elite services such as travel booking, event planning, and more.",
    "how can i contact support": "You can reach support at info@bonet.rw or call +250726300260.",
    "how do i book a flight": "You can book a flight through our travel booking service. Let me know your destination and date of travel!",
    "can you recommend a hotel": "Sure! Let me know your location and preferences, and I'll suggest some great hotels.",
    "do you offer event planning": "Yes! We can help with event planning, from venue booking to logistics management.",
    "can you book a restaurant for me": "Yes, we can! Please provide the restaurant name, date, and time.",
    "do you provide transportation services": "Yes, we can arrange transportation, including airport transfers and city rides.",
    "can you help me find a rental car": "Absolutely! Let us know the location and type of car you need.",
    "what payment methods do you accept": "We accept credit cards, mobile payments, and bank transfers.",
    "do you offer refund policies": "Yes, we have a refund policy. Please check our terms or contact support for details.",
    "can you provide a travel itinerary": "Yes! We can create a travel itinerary based on your preferences.",
    "what are the best tourist attractions nearby": "I can recommend top tourist attractions based on your location and interests!",
    "can you help with visa applications": "Yes, we can guide you through the visa application process.",
    "how do i check my booking status": "You can check your booking status by providing your booking reference number.",
    "do you offer discounts": "Yes, we occasionally offer discounts. Please check our promotions page or ask support.",
    "how do i cancel a booking": "To cancel a booking, please provide your booking reference, and we'll assist you.",
    "can you arrange a private tour": "Yes, we can organize private tours based on your interests.",
    "how do i sign up for your service": "You can sign up on our website or contact support for assistance.",
    "do you offer 24/7 support": "Yes, our support team is available 24/7 to assist you.",
    "can you book an emergency flight": "Yes, we can assist with urgent flight bookings. Please provide details.",
    "how do i leave a review": "You can leave a review on our website or through the feedback section in our app.",
    "can you assist with business travel": "Yes, we provide corporate travel management services.",
    "do you offer honeymoon packages": "Yes! We have special honeymoon travel and accommodation packages.",
    "can you book a cruise": "Yes, we can help book cruises to various destinations.",
    "how do i request a special service": "Please specify your request, and we’ll do our best to accommodate it.",
    "do you provide travel insurance": "Yes, we can help arrange travel insurance for your trip.",
    "can you help with lost baggage": "Yes, we can assist in tracking lost baggage. Please provide your flight details.",
    "what are the best shopping spots near me": "I can suggest top shopping malls and stores based on your location.",
    "do you offer VIP Elite services": "Yes, we offer exclusive VIP Elite services. Contact us for details.",
    "how do i modify my booking": "To modify your booking, provide your reference number and new details.",
    "can you recommend a spa nearby": "Yes! Let me know your location, and I'll find a great spa for you.",
    "how do i get travel updates": "We provide real-time travel updates. Subscribe to our alerts or check our website.",
    "do you offer group travel services": "Yes, we arrange group travel for corporate and leisure trips.",
    "can you help with pet-friendly accommodations": "Of course! Let me know your location, and I’ll find pet-friendly options.",
    "do you provide translation services": "Yes, we can arrange translation services for your travel needs.",
    "can you suggest local cultural experiences": "Absolutely! I can recommend cultural tours and experiences in your area.",
    "do you offer wedding planning services": "Yes, we provide full wedding planning services from venue booking to catering.",
    "how can i get airport lounge access": "We can arrange airport lounge access for you. Let us know your travel details.",
    "what is your cancellation policy": "Our cancellation policy depends on the service booked. Contact support for details.",
    "can you help with emergency medical services": "Yes, we can connect you with local medical assistance.",
    "do you offer corporate event planning": "Yes, we handle corporate events, including conferences and retreats.",
    "can you assist with private jet booking": "Yes, we offer private jet charter services upon request.",
    "how do i get priority check-in at the airport": "We can arrange priority check-in for you. Let us know your airline and flight details.",
    "default": "I'm not sure about that. Can you rephrase or ask something else?",
    "What is an AI-powered website?": "An AI-powered website integrates artificial intelligence features to enhance automation, improve user experience, and streamline operations.",
    "How can AI improve customer support on my website?": "AI can provide chatbots for answering FAQs, assisting with bookings, and guiding users through various processes.",
    "What AI tools can I use for automation on my website?": "Tools like ChatGPT, Dialogflow, Rasa, and IBM Watson can automate customer interactions, while AI analytics tools like Google AI and OpenAI can improve insights.",
    "Can AI handle document processing for my business?": "Yes, AI can assist in setting up and managing business documents through OCR technology, natural language processing, and automated workflows.",
        "What’s the best AI chatbot for customer service?": "Popular options include ChatGPT, Drift, Intercom, and Tidio, which offer advanced conversation handling and automation.",
        "What is an AI chatbot?": "An AI chatbot is a virtual assistant that can answer customer questions, guide users, and automate support functions.",
        "Can an AI chatbot help with business registration?": "Yes, AI chatbots can guide users through the registration process by providing step-by-step instructions.",
        "Can the chatbot handle multiple languages?": "Yes, modern AI chatbots support multiple languages for better customer engagement.",
        "How does an AI chatbot assist with bookings?": "It can check availability, confirm reservations, and handle payments automatically.",
        "Can I integrate AI chatbots into my existing website?": "Yes, AI chatbots can be integrated into most websites via APIs and plugins.",
        "What is an AI-powered booking system?": "It’s an automated system that handles reservations for hotels, transport, and tours.",
        "How does an AI booking system work?": "It checks availability, processes payments, sends confirmations, and suggests alternatives if needed.",
        "Can AI booking systems personalize recommendations?": "Yes, AI can analyze user behavior to provide customized suggestions.",
        "Can AI manage cancellations and refunds?": "Yes, AI-powered systems can process cancellations and issue refunds automatically.",
        "Can I integrate an AI booking system into my current platform?": "Yes, most AI booking systems offer API integrations.",
        "How does AI generate business insights?": "AI analyzes user data, trends, and market behavior to create actionable reports.",
        "What kind of reports can AI generate?": "AI can generate financial, customer behavior, and operational efficiency reports.",
        "Can AI predict sales trends?": "Yes, AI can use historical data and machine learning to predict future sales trends.",
        "How can AI improve decision-making?": "AI processes vast amounts of data quickly, providing insights that aid strategic decisions.",
        "Is AI-generated reporting accurate?": "Yes, AI-driven reports are highly accurate as they analyze real-time data without human errors.",
        "What is AI-powered personalization?": "AI customizes user experiences based on past interactions and preferences.",
        "How does AI recommend products or services?": "AI uses machine learning and behavioral analysis to suggest relevant products or services.",
        "Can AI help target the right audience?": "Yes, AI can analyze customer data to identify and target the most relevant users.",
        "Is AI personalization beneficial for e-commerce?": "Yes, AI increases sales by recommending products based on user behavior.",
        "How does AI improve customer retention?": "By offering personalized experiences, AI keeps users engaged and satisfied.",
        "Can AI answer customer queries using voice?": "Yes, AI voice assistants can handle customer inquiries just like a chatbot.",
        "How does an AI voice assistant work?": "It processes spoken queries using speech recognition and responds using natural language processing.",
        "Can AI voice assistants be integrated into websites?": "Yes, AI voice assistants can be embedded into websites and apps.",
        "Can AI voice assistants handle multiple users simultaneously?": "Yes, they are designed to manage multiple interactions at once.",
        "What are the best AI voice assistants for businesses?": "Google Assistant, Amazon Alexa, and IBM Watson Assistant are top options.",
        "Can AI help with business document creation?": "Yes, AI can generate contracts, invoices, and reports automatically.",
        "Does AI help in document classification?": "Yes, AI can sort and categorize documents based on content.",
        "Can AI extract data from scanned documents?": "Yes, Optical Character Recognition (OCR) technology allows AI to extract text from scanned documents.",
        "Can AI suggest improvements in legal documents?": "Yes, AI can analyze legal documents for errors and suggest modifications.",
        "Is AI document management secure?": "Yes, AI-driven document systems use encryption and authentication for security.",
        "How much does it cost to develop an AI-powered website?": "Costs vary based on complexity, features, and integrations, but AI-powered websites are generally more expensive than regular ones.",
        "How long does it take to integrate AI into a website?": "It depends on the features required; simple chatbots can be integrated in days, while full AI automation may take months.",
        "Is AI integration expensive?": "AI tools vary in price, but some offer cost-effective solutions for small businesses.",
        "Are there free AI tools available?": "Yes, some AI tools like ChatGPT (free tier) and Google Dialogflow have free versions.",
        "Can AI development be outsourced?": "Yes, many AI development companies and freelancers offer integration services.",
        "How secure is an AI-powered website?": "AI-powered websites use encryption, authentication, and security protocols to protect data.",
        "Can AI detect fraudulent activities?": "Yes, AI can identify suspicious activities and prevent fraud in transactions.",
        "Does AI require constant updates?": "Yes, AI models improve over time and require updates to maintain efficiency.",
        "Can AI handle high traffic on websites?": "Yes, AI optimizations ensure smooth performance even during peak traffic.",
    "Does AI work well on mobile websites?": "Yes, AI-powered features are optimized for mobile compatibility.",
    "Is AI the future of website development?": "Yes, AI is becoming increasingly essential for automation and user engagement.",
    "Can AI replace human customer support?": "AI can handle many queries, but human support is still needed for complex issues.",
    "What industries benefit most from AI-powered websites?": "E-commerce, travel, healthcare, finance, and education benefit significantly from AI integration.",
    "Will AI eventually run entire businesses?": "While AI can automate many tasks, human oversight will still be essential.",
    "Can AI help businesses scale faster?": "Yes, AI reduces manual work, optimizes processes, and improves customer engagement, leading to faster business growth.",

  };
  
  export default knowledgeBase;